export default {
    ADD_ANIMAL: 'ADD_ANIMAL',
    SET_ANIMALS: 'SET_ANIMALS',
    DELETE_ANIMAL: 'DELETE_ANIMAL',
    SET_ERROR: 'SET_ERROR',
    SAVE_TOKEN: 'SAVE_TOKEN',
    SET_USER_LOADED: 'SET_USER_LOADED',
    SET_USER: 'SET_USER',
    ADD_GRAPHQL_ERROR: 'ADD_GRAPHQL_ERROR',
};